using UnityEngine;

public enum ShipStatType {
    Power,
    Armor,
    Hull,
    Speed,
    Shields,
    Sensors,
    Luck,
    Charisma,
    DamageBonus,
    CritChanceBonus,
    CritDamageBonus,
    AttackSpeedBonus,
    Accuracy,
    ProjectileSpeedBonus,
    ProjectilePierceNumberBonus,
    ProjectileChainNumberBonus,
    MoveSpeed,
    Size,
    DamageReduction,
    Evasion,
    StatusDurationReduction,
    MaxHealth,
    HealthRegen,
    HealingBonus,
    MaxShields,
    ShieldRegen,
    ShieldRegenTime,
    StatusDurationBonus,
    CurrencyBonus,
    XpBonus,
    CrewCapacity,
    ProjectileSplitNumberBonus,
    LifeSteal,
    IgnoreArmor,
    IgnoreShields,
    ShieldDrain,
    ShieldBurn,
    ProjectileAccelerationBonus,
    AdditionalProjectilesBonus,
    Count
    
}

